name: Lint, Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test-scan
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Lint, Build & Test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
